train_data_config:
  data_files:
    vol_12350:
      image:
        path: "/home/eschomburg/Simons Foundation Dropbox/Erik Schomburg/wasp-em/13_wasp_sample3_neuron/vol_01700/img.h5"
        dataset: "main"
      label:
        path: "/home/eschomburg/Simons Foundation Dropbox/Erik Schomburg/wasp-em/13_wasp_sample3_neuron/vol_01700/label_v3_filled.h5"
        dataset: "main"
  patch_size: [200, 200]
  axis: null
  rng: "she sells sea shells by the sea shore"
sam2_checkpoint: "sam2_hiera_small.pt"
model_cfg: "sam2_hiera_s.yaml"
batch_size: 4
num_batches: 1000
learning_rate: 1.0e-5
weight_decay: 4.0e-5
checkpoint_interval: 1000
display_interval: 100
